version: '3'
services:

  db:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: changeme

  web:
    build: ./app/
    ports:
      - "5000:5000"
    volumes:
      - ./app/:/code
    depends_on:
      - db
